version: '3.0'
services:
  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=university_user
      - POSTGRES_PASSWORD=university_password
      - POSTGRES_DB=university
    ports:
      - '5432:5432'
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=university_user_test
      - POSTGRES_PASSWORD=university_password_test
      - POSTGRES_DB=university_test
    ports:
      - "5433:5432"
networks:
  custom:
    driver: bridge